# 连接数据库的配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybaking?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: lzb2003.228
# 配置Mybatis的XML文件的位置
mybatis:
  mapper-locations: classpath:mappers/*.xml
# 驼峰映射-数据字段和类属性的匹配
  configuration:
    map-underscore-to-camel-case: true
